server:
  port: 8081
spring:
  name: microservicoecadastrarclient
  datasource:
    url: jdbc:postgresql://localhost:5433/client
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  main:
    web-application-type: servlet
  boot:
    run:
      jvmArguments: --add-opens=java.base/java.time=ALL-UNNAMED
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      topics:
        - client-create-topic
      group-id: client-service-group
      auto-offset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer-org: org.apache.kafka.common.serialization.StringDeserializer

