spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/client
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  main:
    web-application-type: servlet
  boot:
    run:
      jvmArguments: --add-opens=java.base/java.time=ALL-UNNAMED
